package com.coleksii.swingy.enums;

public enum State {
    NEW_GAME, CHOICE, CHOOSE_HERO, CREATE_HERO_NAME, START_GAME, INPUT_HERO, FINISH, FIND_MONSTER, GAME_PROCESS, NO_ESCAPE, DEFEAT, ARTIFACT, FIGHT
}
